### ISSUE TITLE
[BUG] Outside mob spawn rates

### ISSUE THREAD

**Issue by ProfX66** [jrremlinger/LC_ToxicOmega_Tools#1]
For some reason this mod is increasing the outside enemy spawn rates often as if the moon was eclipsed but was not.

We would either have dogs and giants already spawned as we landed or would show up before 10am on the clock on standard maps with a brand new save.

I know this mod is meant to test mods and what not, but it does make it frustrating to have to deal with so many outside mobs upon immediately landing on moons while testing mod packs.

I looked at your code but it didn't look like anything you were doing would cause this, but both my friend and I confirmed with just this mod installed alongside its dependencies we see the outside mob spawns being affected.

I also cloned your repo and just commented out your ModifyLevel patches as well as the actual spawn command (really just trying to see if I could affect the outside spawning). Running that version of the DLL, I stopped seeing the outside spawn frequency. Obviously this is a sledge hammer approach but I think something in that patch is causing the base percentage chance to be much higher than it should be.

I can also see the following in the console between versions:
- Unmodified DLL: base chance daytime 4.995485
- Modified DLL: base chance daytime 0.7228957

Both of these log entries occurred shortly after landing on a moon.

I am uncertain what would cause these chances to be different, as at first glance I don't see anything in your code touching those but either way I figured I would report what we are seeing.

Here is the pack code we were using to test: 018d1dc9-bac3-8a37-cc3a-c078e93ce1a2

**Comment by jrremlinger** [comment]
Hello, sorry just seeing this now! Will look into it, definitely seems odd...

**Comment by jrremlinger** [comment]
Issue has been resolved in commit [1b128a8](https://github.com/jrremlinger/LC_ToxicOmega_Tools/commit/1b128a861e16f036d7662eb40ea2f6e6498d8668). Pushed in update v1.1.7
